apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: mysqldb
        image: vijayadk/bloodapp:appimage
        ports:
        - containerPort: 80
        env:
            - name: DB_HOST
              value: mysqldb
        resources:
          requests:
            memory: "256Mi"  # Minimum memory requested
            cpu: "250m"      # Minimum CPU requested (0.25 core)
          limits:
            memory: "512Mi"  # Maximum memory allowed
            cpu: "500m"
      imagePullSecrets:
            - name: dockerhub-secret
